data:
  gpu: 0
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  log_level: 1
lr:
  lr: 0.1
  lr_schedule_type: step
model:
  arch: resnet18
resolution:
  max_res: 224
  min_res: 224
training:
  batch_size: 1024
  bn_wd: 0
  distributed: 0
  epochs: 90
  label_smoothing: 0
  momentum: 0.9
  optimizer: sgd
  weight_decay: 1e-4
  use_blurpool: 0
  seed: 0
  frac_percent: 0.1
  freq: 10
validation:
  lr_tta: 0
  resolution: 256
